name: Pipeline Frontend Wuepa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compilar frontend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Compilar aplicacion
        run: npm run build

      - name: Guardar archivos compilados
        uses: actions/upload-artifact@v4
        with:
          name: frontend-wuepa-dist
          path: dist
          if-no-files-found: error
